"""init

Revision ID: ea23077510a7
Revises:
Create Date: 2023-12-18 18:31:22.231803

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = 'ea23077510a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
