"""add questions body unique constraint

Revision ID: 59e6ca0ab0d0
Revises: 3dd1b3c0e39c
Create Date: 2023-12-18 20:46:54.809938

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '59e6ca0ab0d0'
down_revision: Union[str, None] = '3dd1b3c0e39c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'questions', ['body'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='unique')
    # ### end Alembic commands ###
