"""add answers is_correct field

Revision ID: e602beefc86b
Revises: 59e6ca0ab0d0
Create Date: 2023-12-18 22:44:54.298557

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e602beefc86b'
down_revision: Union[str, None] = '59e6ca0ab0d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('is_correct', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'is_correct')
    # ### end Alembic commands ###
